### ISSUE TITLE
Add support for Prisma's multiSchema feature

### ISSUE THREAD

**Issue by Jens-Rydholm-Humly** [loop-payments/prisma-lint#518]
Hello team,

For applications using Prisma's `multiSchema` preview feature (see https://www.prisma.io/docs/orm/prisma-schema/data-model/multi-schema), it seems `prisma-lint` doesn't currently work. As larger data models that benefit from splitting into multiple schemas would also benefit a lot from linting, I feel this would be a useful addition.

When we try on a repo using multiple schemas (and also using multiple files, see https://github.com/loop-payments/prisma-lint/issues/508), we get the following error (on version `0.7.0`):
```
TypeError: Cannot read properties of undefined (reading 'value')
    at extractPrimaryFieldNameFromRelationListAttribute (file:///Users/jensrydholm/Workspace/humly-api/node_modules/.pnpm/prisma-lint@0.7.0_typescript@5.6.3/node_modules/prisma-lint/dist/rules/require-field-index.js:183:20)
    at file:///Users/jensrydholm/Workspace/humly-api/node_modules/.pnpm/prisma-lint@0.7.0_typescript@5.6.3/node_modules/prisma-lint/dist/rules/require-field-index.js:162:21
    at Array.forEach (<anonymous>)
    at extractIndexSet (file:///Users/jensrydholm/Workspace/humly-api/node_modules/.pnpm/prisma-lint@0.7.0_typescript@5.6.3/node_modules/prisma-lint/dist/rules/require-field-index.js:157:21)
    at getIndexSet (file:///Users/jensrydholm/Workspace/humly-api/node_modules/.pnpm/prisma-lint@0.7.0_typescript@5.6.3/node_modules/prisma-lint/dist/rules/require-field-index.js:110:60)
    at Object.Field (file:///Users/jensrydholm/Workspace/humly-api/node_modules/.pnpm/prisma-lint@0.7.0_typescript@5.6.3/node_modules/prisma-lint/dist/rules/require-field-index.js:127:38)
    at file:///Users/jensrydholm/Workspace/humly-api/node_modules/.pnpm/prisma-lint@0.7.0_typescript@5.6.3/node_modules/prisma-lint/dist/lint-prisma-source-code.js:43:34
    at Array.forEach (<anonymous>)
    at file:///Users/jensrydholm/Workspace/humly-api/node_modules/.pnpm/prisma-lint@0.7.0_typescript@5.6.3/node_modules/prisma-lint/dist/lint-prisma-source-code.js:42:24
    at Array.forEach (<anonymous>)
```

**Comment by Jens-Rydholm-Humly** [comment]
Each of our files have a single schema, but there are indeed foreign keys (mapped as Prisma `@relation`) between them. There is also a `schema.prisma` file that only contains the `generator` and `datasource` configuration.

So, it looks like this (anonymised). As you can imagine, several models in other schemas have relations to the `users` schema (and there are other relations as well):
```
% grep "@@schema" prisma/schema/*.prisma | uniq
prisma/schema/foo.prisma:  @@schema("foo")
prisma/schema/bar.prisma:  @@schema("bar")
prisma/schema/fum.prisma:  @@schema("fum")
prisma/schema/users.prisma:  @@schema("users")
```

If this is not enough to reproduce the issue, I can set up a repo when I have the time to do so.
